spring:
  application:
    name: fanmon_be
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PWD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 최대 파일 사이즈 설정
      max-request-size: 10MB  # 최대 요청 사이즈 설정
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      hibernate: debug
    root: warn
    org.springframework: warn
    org.hibernate: warn